[package]
name = "migrate-js-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = "0.17.3"
serde_json = "1.0.78"
serde = { version = "1.0.130", features = ["derive"] }
url = "2.2.2"